Update: Translate messages into English.
egal/egal-framework-php-package pull request #83
Opened 2021-07-30 08:51 UTC by futenute

2021-07-30 09:05 UTC, rollsover requested changes

2021-07-30 09:05 UTC, rollsover commented on exception/IrreversibleMigrationException.php
> - * @deprecated
Нужно вернуть и написать причину устаревания : `@depricated from v2.0.0`.

2021-07-30 09:05 UTC, rollsover commented on exception/ModelException.php
> - * @deprecated
Нужно вернуть и написать причину устаревания : `@depricated from v2.0.0`.

2021-07-30 09:05 UTC, rollsover commented on exception/WhereException.php
> - * @deprecated
Нужно вернуть и написать причину устаревания : `@depricated from v2.0.0`.

2021-07-30 09:05 UTC, rollsover commented on model/Filter/FilterCombiner.php
> +        if (!self::mayMakeFromString($string)) {
Заменить на static.

2021-07-30 09:05 UTC, rollsover commented on model/Filter/FilterPart.php
> +                $filterPart->addContentItem(self::fromArray($item));
Заменить на static.

2021-07-30 09:11 UTC, l-max commented on code-generator/Commands/RuleMakeCommand.php
> +    protected $description = 'Генерация класса правила валидации';
Может названия команд тоже на английском сделаем сразу?

2021-07-30 09:11 UTC, l-max commented on core/Exceptions/EgalCoreInitializationException.php
> +declare(strict_types=1);
А зачем нам strict_types в классах исключении? 
Шибко важной логики в них нет, не думаю что есть какой то толк от этого

2021-07-30 09:14 UTC, rollsover commented on core/Exceptions/EgalCoreInitializationException.php
> +declare(strict_types=1);
Это требование будет у нас всегда, строгая типизация все дела

2021-07-30 09:18 UTC, l-max commented on model/Exceptions/HashGuardException.php
> +    protected $message = 'Hash guard Exception!';
Мне кажется что все слова кроме первого должны быть с маленькой буквы.

2021-07-30 11:48 UTC, futenute commented on core/Exceptions/InitializeMessageFromArrayException.php
> +    protected $message = 'Initialize message from array Exception';
Добавила

2021-07-30 11:48 UTC, futenute commented on core/Exceptions/QueueProcessingException.php
> +    protected $message = 'Queue processing Exception';
Добавила

2021-07-30 11:49 UTC, futenute commented on exception/IrreversibleMigrationException.php
> - * @deprecated
Вернула

2021-07-30 11:49 UTC, futenute commented on exception/ModelException.php
> - * @deprecated
Вернула

2021-07-30 11:49 UTC, futenute commented on exception/WhereException.php
> - * @deprecated
Вернула

2021-07-30 11:49 UTC, futenute commented on model/Filter/FilterCombiner.php
> +        if (!self::mayMakeFromString($string)) {
Заменила

2021-07-30 11:51 UTC, futenute commented on model/Filter/FilterPart.php
> +                $filterPart->addContentItem(self::fromArray($item));
Не нужно.

2021-07-30 11:52 UTC, futenute commented on code-generator/Commands/RuleMakeCommand.php
> +    protected $description = 'Генерация класса правила валидации';
Решили сделать это в другой задаче.

2021-07-30 11:52 UTC, futenute commented on model/Exceptions/HashGuardException.php
> +    protected $message = 'Hash guard Exception!';
Исправлено.

2021-08-01 19:02 UTC, rollsover commented on code-generator/Commands/RuleMakeCommand.php
> +    protected $description = 'Генерация класса правила валидации';
Завели задачу?

2021-08-01 19:02 UTC, rollsover commented on core/Exceptions/EgalCoreInitializationException.php
> +declare(strict_types=1);
Ждем ответа.

2021-08-01 19:03 UTC, rollsover commented on model/Filter/FilterPart.php
> +                $filterPart->addContentItem(self::fromArray($item));
Обсудили, класс `final` не нуждается.

2021-08-01 19:06 UTC, rollsover approved these changes

2021-08-02 03:53 UTC, futenute commented on code-generator/Commands/RuleMakeCommand.php
> +    protected $description = 'Генерация класса правила валидации';
https://github.com/egal/egal-framework-php-package/issues/86

2021-08-02 04:10 UTC, l-max commented on core/Exceptions/EgalCoreInitializationException.php
> +declare(strict_types=1);
Как знаете. Мне кажется в этих классах это лишнее.

2021-08-02 04:10 UTC, l-max approved these changes

2021-08-02 04:11 UTC, merged